### ISSUE TITLE
Wicketstuff.org site is outdated

### ISSUE THREAD

**Issue by keesvandieren** [wicketstuff/wicketstuff.github.com#1]
http://wicketstuff.org/ is no longer maintained, while the code is still maintained.

This makes visitors think wicketstuff is no longer maintained, and does not support Wicket 7 / 8 / 9.

Please either remove the site (e.g. redirect to github project) or make it up-to-date. Let PMC make the decision.

**Comment by bitstorm** [comment]
For the moment I've removed the reference to http://wicketstuff.org/ from the WicketStuff readme.md, so the GitHub homepage is no more deceiving.

**Comment by chrisco484** [comment]
Would it be possible to autogenerate the content for wicketstuff.org somehow and update each time it is released?

That's what the [DataNucleus](http://www.datanucleus.org/) website does - the website contents/doco/examples are built with the framework and released to the website with each release.

**Comment by martin-g** [comment]
+1 to update `index.html` with the supported versions.
I do not see what could/should be autogenerated. Most of the projects' docu is in the Wiki pages and in their `-examples` sub-modules.

**Comment by keesvandieren** [comment]
also update copyright year to 2019 then :)
